name: LVGL_MicroPython For ESP32S3

on:
  workflow_dispatch:

env:
  LVGL: lvgl_micropython
  LVGL_REPO: https://github.com/lvgl-micropython/lvgl_micropython.git
  TZ: Asia/Shanghai

jobs:
  LVGL_MicroPython-ESP32S3:
    name: Build LVGL_MicroPython
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        info:
          #- '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "16",  "DISPLAY": "st7789",  "INDEV":"" }'
          #- '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "16",  "DISPLAY": "st7789",  "INDEV":"ft6x36" }'
          #- '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "16",  "DISPLAY": "st7796",  "INDEV":"" }'
          - '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "16",  "DISPLAY": "ili9341",  "INDEV":"" }'
          #- '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "8",   "DISPLAY": "ili9341", "INDEV":"ft6x36" }'
          #- '{ "BOARD": "ESP32_GENERIC_S3",  "BOARD_VARIANT": "SPIRAM_OCT",  "FLASH": "16",  "DISPLAY": "gc9a01",  "INDEV":"" }'
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential libffi-dev git pkg-config
          sudo apt-get install -y git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 python-is-python3 pip
          sudo timedatectl set-timezone "${{env.TZ}}"

      - name: Clone LVGL
        run: |
          git clone --depth=1 ${{env.LVGL_REPO}} ${{env.LVGL}}

      - name: Compile the firmware
        id: compile
        run: |
          cd ${{env.LVGL}}
          if ["${{fromJSON(matrix.info).INDEV}}" == ""]; then
            echo "python3 make.py esp32 BOARD=${{fromJSON(matrix.info).BOARD}} BOARD_VARIANT=${{fromJSON(matrix.info).BOARD_VARIANT}} --flash-size=${{fromJSON(matrix.info).FLASH}} DISPLAY=${{fromJSON(matrix.info).DISPLAY}}"
            python3 make.py esp32 BOARD=${{fromJSON(matrix.info).BOARD}} BOARD_VARIANT=${{fromJSON(matrix.info).BOARD_VARIANT}} --flash-size=${{fromJSON(matrix.info).FLASH}} DISPLAY=${{fromJSON(matrix.info).DISPLAY}}
          else
            echo "python3 make.py esp32 BOARD=${{fromJSON(matrix.info).BOARD}} BOARD_VARIANT=${{fromJSON(matrix.info).BOARD_VARIANT}} --flash-size=${{fromJSON(matrix.info).FLASH}} DISPLAY=${{fromJSON(matrix.info).DISPLAY}} INDEV=${{fromJSON(matrix.info).INDEV}}"
            python3 make.py esp32 BOARD=${{fromJSON(matrix.info).BOARD}} BOARD_VARIANT=${{fromJSON(matrix.info).BOARD_VARIANT}} --flash-size=${{fromJSON(matrix.info).FLASH}} DISPLAY=${{fromJSON(matrix.info).DISPLAY}} INDEV=${{fromJSON(matrix.info).INDEV}}
          fi
         echo "FIREMWARE=LVGL_MicroPython-${{fromJSON(matrix.info).BOARD}}_${{fromJSON(matrix.info).BOARD_VARIANT}}_N${{fromJSON(matrix.info).FLASH}}_${{fromJSON(matrix.info).DISPLAY}}_${{fromJSON(matrix.info).INDEV}}_$(date +%Y%m%d).bin" >> $GITHUB_ENV
          echo "OUTPUT=${{env.LVGL}}/build" >> $GITHUB_ENV
          echo "FIREMWARE_ORIGIN=lvgl_micropy_${{fromJSON(matrix.info).BOARD}}-${{fromJSON(matrix.info).BOARD_VARIANT}}-${{fromJSON(matrix.info).FLASH}}.bin" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT
          echo "COMPILE_DATE=$(date +\"%Y%m%d\")" >> $GITHUB_ENV

      - name: Organize compiled firmware
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          mkdir -p firmware
          mv ${{env.OUTPUT}}/${{env.FIREMWARE_ORIGIN}} firmware/${{env.FIREMWARE}}

      - name: Upload firmware to artifacts
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: LVGL_MicroPython-${{fromJSON(matrix.info).BOARD}}_${{fromJSON(matrix.info).BOARD_VARIANT}}_N${{fromJSON(matrix.info).FLASH}}_${{fromJSON(matrix.info).DISPLAY}}_${{fromJSON(matrix.info).INDEV}}
          path: firmware/${{env.FIREMWARE}}
          retention-days: 30

  Delete_Workflow:
    needs: [ LVGL_MicroPython-ESP32S3 ]
    runs-on: ubuntu-22.04
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 4
